CREATE TABLE budget
(
    budget_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    days_in_month INTEGER NOT NULL,
    savings DOUBLE PRECISION NOT NULL,
    start_date TIMESTAMP NOT NULL
);

CREATE TABLE member
(
    member_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    enabled BOOLEAN DEFAULT 't' NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE expense
(
    expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_amount DOUBLE PRECISION NOT NULL,
    payed BOOLEAN DEFAULT 'n' NOT NULL,
    type VARCHAR(30),
    expense_description VARCHAR(255),
    pay_date TIMESTAMP,
    budget_id BIGINT NOT NULL,
    FOREIGN KEY (budget_id) REFERENCES budget (budget_id)
);

CREATE TABLE income
(
    income_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    income_amount DOUBLE PRECISION NOT NULL,
    type VARCHAR(30) NOT NULL,
    budget_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    FOREIGN KEY (budget_id) REFERENCES budget (budget_id),
    FOREIGN KEY (member_id) REFERENCES member (member_id)
);

CREATE TABLE invitation
(
    invitation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message VARCHAR(255) NOT NULL,
    budget_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    FOREIGN KEY (budget_id) REFERENCES budget (budget_id),
    FOREIGN KEY (receiver_id) REFERENCES member (member_id),
    FOREIGN KEY (sender_id) REFERENCES member (member_id)
);

CREATE TABLE budget_members
(
    budgets_id BIGINT NOT NULL,
    users_id BIGINT NOT NULL,
    FOREIGN KEY (budgets_id) REFERENCES budget (budget_id),
    FOREIGN KEY (users_id) REFERENCES member (member_id)
);